import 'package:flutter/material.dart';
import 'package:littletech/src/features/game/constants/game_data.dart';
import 'package:littletech/src/features/game/constants/boss_encounter_data.dart';

class CategoryDef {
  final String id;
  final String name;
  final IconData icon;
  final String description;
  final List<String> problemKeys;
  final int levelCount;
  final String bossName;
  final String bossLore;
  final int bossHp;
  final List<BossEncounterDef> bosses;

  const CategoryDef({
    required this.id,
    required this.name,
    required this.icon,
    required this.description,
    required this.problemKeys,
    this.levelCount = 29,
    this.bossName = '',
    this.bossLore = '',
    this.bossHp = 5,
    this.bosses = const [],
  });
}

class CategoryManager {
  static const List<CategoryDef> all = [
    CategoryDef(
      id: 'core_components',
      name: 'Core Components',
      icon: Icons.memory,
      description: 'CPU, motherboard, RAM basics',
      problemKeys: [
        'high cpu usage',
        'cpu overheating',
        'computer not turning on',
        'beep codes on startup',
        'cpu fan not spinning',
        'cpu not detected in bios',
        'overclocking unstable',
        'motherboard cmos battery dead',
        'power supply failure',
        'pcie slot not working',
        'gpu not detected',
        'bios recovery needed',
        'hardware compatibility issue',
        'driver installation failed',
        'usb port not working',
        'case airflow poor',
        'thermal throttling',
        'memory overclock failed',
        'cpu upgrade needed',
        'pc randomly restarts',
        'no power button response',
        'motherboard speaker silent',
        'cpu cooler rgb not lighting',
        'nvme ssd not recognized',
        'system freezes on boot',
      ],
      levelCount: 29,
      bossName: 'The Bone Colossus',
      bossLore:
          'A towering skeleton giant assembled from broken PC cases and failed hardware.',
      bossHp: 5,
      bosses: coreComponentsBosses,
    ),
    CategoryDef(
      id: 'ram',
      name: 'RAM',
      icon: Icons.developer_board,
      description: 'Memory issues and upgrades',
      problemKeys: [
        'random crashes / bsod',
        'insufficient memory warning',
        'ram not detected',
        'ram overheating',
        'ram compatibility issues',
        'memory overclock unstable',
        'dual channel not working',
        'ram latency issues',
        'memory leak detection',
        'ecc memory error',
        'ram speed mismatch',
        'memory module defective',
        'xmp profile fails',
        'ram slot damaged',
        'memory test failed',
      ],
      levelCount: 29,
      bossName: 'The Memory Wraith',
      bossLore:
          'A ghostly entity that corrupts memory addresses and shreds data.',
      bossHp: 5,
      bosses: ramBosses,
    ),
    CategoryDef(
      id: 'operating_system',
      name: 'Operating System',
      icon: Icons.desktop_windows,
      description: 'Boot issues and OS problems',
      problemKeys: [
        "pc won't boot",
        'boot loop',
        'blue screen of death (bsod)',
        'os running slow',
        'windows not updating',
        'system restore failed',
        'safe mode stuck',
        'registry corruption',
        'missing dll error',
        'application crash loop',
        'startup repair stuck',
        'user profile corrupted',
        'activation failed',
        'kernel security check',
        'driver verifier crash',
      ],
      levelCount: 29,
      bossName: 'The Lich Lord',
      bossLore: 'An undead sorcerer of corrupted system files.',
      bossHp: 6,
      bosses: operatingSystemBosses,
    ),
    CategoryDef(
      id: 'audio',
      name: 'Audio',
      icon: Icons.volume_up,
      description: 'Sound and speaker issues',
      problemKeys: [
        'no sound output',
        'distorted audio',
        'audio device not found',
        'microphone not working',
        'audio lag / delay',
        'headphones only one side',
        'bluetooth audio choppy',
        'sound randomly cuts out',
        'realtek audio missing',
        'spatial sound not working',
        'audio crackling noise',
        'volume slider disabled',
        'sound services stopped',
        'audio driver rollback',
        'dolby atmos not working',
      ],
      levelCount: 29,
      bossName: 'The Static Specter',
      bossLore:
          'A ghost that feeds on audio frequencies and corrupts sound waves.',
      bossHp: 5,
      bosses: audioBosses,
    ),
    CategoryDef(
      id: 'peripherals',
      name: 'Peripherals',
      icon: Icons.mouse,
      description: 'Mouse, keyboard, printer issues',
      problemKeys: [
        'mouse not responding',
        'cursor lagging or stuttering',
        'mouse double-click issue',
        'keyboard not responding',
        'printer not responding',
        'paper jam',
        'webcam not working',
        'headset mic muted',
        'usb hub overload',
        'gaming controller drift',
        'touchpad freezing',
        'scanner not detected',
        'external drive slow',
        'bluetooth mouse lag',
        'wireless keyboard delay',
      ],
      levelCount: 29,
      bossName: 'The Goblin King',
      bossLore: 'A cunning goblin warlord that sabotages your peripherals.',
      bossHp: 5,
      bosses: peripheralsBosses,
    ),
    CategoryDef(
      id: 'software',
      name: 'Software',
      icon: Icons.apps,
      description: 'Program and application issues',
      problemKeys: [
        'program crashes on launch',
        'software installation failed',
        'program running slow',
        'dll file missing error',
        'program not compatible',
        'app won\'t open',
        'license expired',
        'subscription not recognized',
        'cloud sync failed',
        'auto updater stuck',
        'portable app crash',
        'antivirus conflict',
        'windows store error',
        'registry cleaner needed',
        'software permission denied',
      ],
      levelCount: 29,
      bossName: 'The Glitch',
      bossLore:
          'A digital parasite that corrupts code and breaks installations.',
      bossHp: 5,
      bosses: softwareBosses,
    ),
    CategoryDef(
      id: 'internet',
      name: 'Internet',
      icon: Icons.wifi,
      description: 'Network and connectivity issues',
      problemKeys: [
        'no internet connection',
        'slow internet speed',
        'wi-fi not detected',
        'dns server not responding',
        'vpn not connecting',
        'ethernet cable unplugged',
        'ip address conflict',
        'router admin locked',
        'bandwidth throttling',
        'packet loss detected',
        'proxy not working',
        'ftp connection failed',
        'ssh timeout error',
        'ping high latency',
        'port forwarding stuck',
      ],
      levelCount: 29,
      bossName: 'The Dragon Whelp',
      bossLore: 'A young crimson dragon that hoards network packets.',
      bossHp: 6,
      bosses: internetBosses,
    ),
    CategoryDef(
      id: 'storage',
      name: 'Storage',
      icon: Icons.storage,
      description: 'Hard drive and storage issues',
      problemKeys: [
        'hard drive not detected',
        'slow disk performance',
        'disk full — no space',
        'clicking or grinding noise',
        'corrupted files / sectors',
        'ssd write protection',
        'disk defragmentation stuck',
        'storage pool degraded',
        'file system error',
        'disk cleanup hanging',
        'partition not mounting',
        'raid array failed',
        'backup incomplete',
        'drive letter missing',
        'disk read error',
      ],
      levelCount: 29,
      bossName: 'The Void Disk',
      bossLore: 'An ancient data-destroyer that consumes files whole.',
      bossHp: 5,
      bosses: storageBosses,
    ),
    CategoryDef(
      id: 'display',
      name: 'Display',
      icon: Icons.monitor,
      description: 'Monitor and screen issues',
      problemKeys: [
        'no display output',
        'flickering screen',
        'black screen on boot',
        'wrong resolution',
        'dead pixels',
        'screen too dim',
        'color calibration off',
        'refresh rate stuck',
        'hdr not working',
        'multiple monitor issue',
        'display adapter error',
        'oled burn in',
        'monitor input lag',
        'g-sync not working',
        'display driver crash',
      ],
      levelCount: 29,
      bossName: 'The Beholder',
      bossLore: 'A floating eye tyrant that corrupts displays.',
      bossHp: 7,
      bosses: displayBosses,
    ),
    CategoryDef(
      id: 'mobile',
      name: 'Mobile',
      icon: Icons.phone_android,
      description: 'Phone and tablet troubleshooting',
      problemKeys: [
        'battery draining too fast',
        'phone overheating',
        'apps crashing on phone',
        'phone not charging',
        'slow phone performance',
        'mobile data not working',
        'wifi calling failed',
        'nfc not working',
        'fingerprint scanner error',
        'face unlock failed',
        'app notification missing',
        'battery health degraded',
        'over the air update failed',
        'sim card not detected',
        'bluetooth pairing failed',
      ],
      levelCount: 29,
      bossName: 'The Battery Wraith',
      bossLore: 'A ghostly energy-draining entity.',
      bossHp: 5,
      bosses: mobileBosses,
    ),
    CategoryDef(
      id: 'gaming',
      name: 'Gaming',
      icon: Icons.sports_esports,
      description: 'Gaming PC and console issues',
      problemKeys: [
        'game crashing on startup',
        'low fps in games',
        'controller not connecting',
        'game audio stuttering',
        'graphics driver crash',
        'game freezing mid-play',
        'shader compilation error',
        'anti-cheat false positive',
        'game overlay conflict',
        'dlss not working',
        'ray tracing crash',
        'vram allocation error',
        'game save corrupted',
        'multiplayer connection failed',
        'achievement not unlocking',
      ],
      levelCount: 29,
      bossName: 'The Lag Dragon',
      bossLore: 'A corrupted game entity that spawns frame drops.',
      bossHp: 6,
      bosses: gamingBosses,
    ),
    CategoryDef(
      id: 'smart_home',
      name: 'Smart Home',
      icon: Icons.home_max,
      description: 'IoT devices and smart home',
      problemKeys: [
        'smart device offline',
        'voice assistant not responding',
        'smart light not connecting',
        'home hub setup failed',
        'automation not triggering',
        'smart lock jammed',
        'thermostat not syncing',
        'smart plug unresponsive',
        'hue bridge not found',
        'alexa routine failed',
        'google home offline',
        'smart speaker muted',
        'ir blaster not working',
        'zigbee network down',
        'mqtt broker error',
      ],
      levelCount: 29,
      bossName: 'The Static Phantom',
      bossLore:
          'A spectral presence that possesses smart devices, making them unresponsive.',
      bossHp: 5,
      bosses: smartHomeBosses,
    ),
    CategoryDef(
      id: 'security',
      name: 'Security',
      icon: Icons.shield,
      description: 'Virus and security threats',
      problemKeys: [
        'virus or malware infection',
        'suspicious pop-ups and browser redirects',
        'firewall blocking legitimate apps',
        'password not accepted after update',
        'wi-fi network showing unauthorized devices',
        'ransomware encryption',
        'trojan detected',
        'spyware infection',
        'rootkit hidden process',
        'phishing attack blocked',
        'security certificate expired',
        'two factor auth failed',
        'encryption key lost',
        'security scan hanging',
        'malware removal tool crash',
      ],
      levelCount: 29,
      bossName: 'The Trojan Imp',
      bossLore: 'A deceptive imp that disguises itself as legitimate software.',
      bossHp: 7,
      bosses: securityBosses,
    ),
    CategoryDef(
      id: 'networking',
      name: 'Networking',
      icon: Icons.router,
      description: 'Routers, switches, DNS, VPN, firewalls',
      problemKeys: [
        'dns lookup failing',
        'dhcp not assigning ip',
        'vpn tunnel drops',
        'port scan detected',
        'firewall rule corruption',
        'nat translation error',
        'bandwidth being drained',
        'routing loop detected',
        'wifi signal disappearing',
        'bgp route hijacked',
        'iot botnet infection',
        'protocol stack corruption',
        'network total lockdown',
        'switch loop detected',
        'cable certification failed',
      ],
      levelCount: 29,
      bossName: 'The DNS Gremlin',
      bossLore:
          'A mischievous gremlin that corrupts DNS lookups, sending devices to wrong addresses.',
      bossHp: 5,
      bosses: networkingBosses,
    ),
  ];

  static CategoryDef? byId(String id) {
    for (final c in all) {
      if (c.id == id) return c;
    }
    return null;
  }
}
